import type { Metadata, Viewport } from "next";
import { ThemeProvider } from "@material-tailwind/react"
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/styles/globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width'
}

export default function RootLayout({ children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          {/* <Link href='/'><h1 className="text-4x1 font-bold underline">Top page layout</h1></Link> */}
        </nav>
        <main className="min-h-screen flex-col justify-between p-14">{children}</main>

      </body>
    </html>
  );
}
