import createClient from "openapi-fetch";
import type { paths } from "@/interfaces/grocy.d"; // generated by openapi-typescript

export const grocyClient = createClient<paths>({ baseUrl: process.env.GROCY_API_URL });