import createClient, { Middleware } from "openapi-fetch";
import type { paths } from "@/interfaces/grocy.d"; // generated by openapi-typescript
import { Dispatch, SetStateAction } from "react";
import { Option } from "@/interfaces";

let baseUrl = process.env.GROCY_API_URL;
if (baseUrl === undefined) {
  baseUrl = process.env.NEXT_PUBLIC_GROCY_API_URL;
}
if (baseUrl === undefined) {
  throw new Error("GROCY_API_URL is not configured");
}

let apiKey = process.env.GROCY_API_KEY;
if (apiKey === undefined) {
  apiKey = process.env.NEXT_PUBLIC_GROCY_API_KEY;
}
if (apiKey === undefined) {
  throw new Error("GROCY_API_KEY is not configured");
}

const myMiddleware: Middleware = {
  async onRequest({ request, options }) {
    request.headers.set("GROCY-API-KEY", apiKey);
    request.headers.set("Accept", "application/json");
    return request;
  },
  async onResponse({ request, response, options }) {
    const { body, ...resOptions } = response;
    // change status of response
    return new Response(body, { ...resOptions, status: 200 });
  },
  async onError({ error }) {
    // wrap errors thrown by fetch
    return new Error("Oh noes, fetch failed", { cause: error });
  },
};

export const grocyClient = createClient<paths>({ baseUrl: baseUrl });
grocyClient.use(myMiddleware);

export function EntityObjectsToOptions({
  selectedIndex,
  entityObjects,
  setSelectedOption,
}: {
  selectedIndex?: number;
  setSelectedOption: Dispatch<SetStateAction<Option | null>>;
  entityObjects: any;
}): Option[] {
  if (entityObjects === undefined) return [];

  const options = entityObjects.map((group: any) => ({
    value: group.id,
    label: group.name,
  }));

  if (selectedIndex !== undefined && selectedIndex !== null && selectedIndex >= 0) {
    const optionIndex: number = options.findIndex((n: Option) => {
      return n.value.toString() === selectedIndex?.toString();
    });

    if (options[optionIndex] !== undefined) {
      setSelectedOption(options[optionIndex]);
    }
  }

  return options;
}
